# Generated by Django 3.0.5 on 2020-05-10 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers_app', '0006_auto_20200510_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencersinformation',
            name='channel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='influencers_app.Influencer'),
        ),
    ]
