# Generated by Django 3.0.5 on 2020-05-10 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencers_app', '0007_influencersinformation_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencersinformation',
            name='responsible',
        ),
        migrations.AddField(
            model_name='influencer',
            name='responsible',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
