# Generated by Django 3.0.5 on 2020-06-29 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers_app', '0010_auto_20200616_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='channel_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='influencers_app.Influencer'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_of_publication',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
