# Generated by Django 3.0.5 on 2020-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("influencers_app", "0012_auto_20200701_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="influencersinformation",
            name="location",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
