# Generated by Django 3.0.5 on 2020-07-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers_app', '0017_shipment_shipmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.ManyToManyField(related_name='products', to='influencers_app.ArtzProductUS'),
        ),
        migrations.DeleteModel(
            name='ShipmentItem',
        ),
    ]
